### ISSUE TITLE
Android demo crash : No implementation found for boolean com.facebook.igl.shell.SampleLib.isBackendTypeIDSupported(int)

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#182]
```java
     java.lang.UnsatisfiedLinkError: No implementation found for boolean com.facebook.igl.shell.SampleLib.isBackendTypeIDSupported(int) (tried Java_com_facebook_igl_shell_SampleLib_isBackendTypeIDSupported and Java_com_facebook_igl_shell_SampleLib_isBackendTypeIDSupported__I) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at com.facebook.igl.shell.SampleLib.isBackendTypeIDSupported(Native Method)
                                                                                                    	at com.facebook.igl.shell.SampleActivity.onCreate(SampleActivity.java:54)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8657)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8636)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4165)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4340)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2584)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8810)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by vinsentli** [comment]
@EricGriffith @rokuz 
There are two sets of code(SampleActivity.java, SampleView.java, SampleLib.java, VulkanView.java) in directories [build/android/app/src/main] and [shell/android], with the outdated one located in directory [build/android/app/src/main].
This outdated code in directory [build/android/app/src/main] is causing the problem.
